server:
  port: 10088
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-password: password
#    key-store-type: PKCS12
#    key-alias: alias
#  http2:
#    enabled: true

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          # 仅在开发环境设置为*
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: userInfo
          uri: lb://user-inform-server
          predicates:
            - Path=/user-info/**
        - id: userPermission
          uri: lb://user-permission-server
          predicates:
            - Path=/userPermission/**
        - id: userMessage
          uri: lb://chat-server
          predicates:
            - Path=/message/**
        - id: userOperation
          uri: lb://user-operation
          predicates:
            - Path=/relation/**

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/

#eureka:
#  client:
#    service-url:
#        defaultZone: http://127.0.0.1:10086/eureka/